config:
  jetstream:
    enabled: true
    fileStore:
      pvc:
        enabled: true
        size: 5Gi
        storageClassName: local-path
  cluster:
    enabled: false
container:
  merge:
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 512Mi
