apiVersion: v1
kind: Namespace
metadata:
  name: sre-system
  labels:
    app.kubernetes.io/part-of: autonomous-sre
---
apiVersion: v1
kind: Namespace
metadata:
  name: demo
  labels:
    app.kubernetes.io/part-of: autonomous-sre
---
apiVersion: v1
kind: Namespace
metadata:
  name: observability
  labels:
    app.kubernetes.io/part-of: autonomous-sre
